### ISSUE TITLE
CPUX64 not implemented MyAllMethodsHandler

### ISSUE THREAD

**Issue by irzyxa** [remobjects/pascalscript#78] opened 2014-05-06 12:44 UTC
In module uPSRuntime.pas not implemented method MyAllMethodsHandler. And don't work event on button click.

**Comment by irzyxa** [comment] 2015-03-11 11:37
Don't work event OnClick in components TButton, TRadioButton (Delphi XE2 X64)

**Comment by carlokok** [comment] 2015-03-11 12:30
Right; this isn't implemented for x64.

**Comment by Andyk123** [comment] 2015-11-11 16:49
Will this ever be supported ?
Its pretty important to me, I don't want to waste too long with PascalScript if its never going to function properly.

**Comment by carlokok** [comment] 2015-11-11 17:00
There's no plan from our side to support this feature. But patches are always welcome.

**Comment by Andyk123** [comment] 2015-11-23 09:58
I can't fix it directly, but I did a bit of digging and have a solution that works for at least 2 parameters.

function MyAllMethodsHandler2(Self:PScriptMethodInfo; const Stack:PPointer; _EDX,_ECX:Pointer):Integer; forward;

{$ifdef CPUX64}
procedure MyAllMethodsHandler;
//  On entry:
//  RCX = Self pointer
//  RDX, R8, R9 = param1 .. param3
//  STACK = param4... paramcount
asm
  PUSH  R9
  MOV   R9,R8     // R9:=_ECX
  MOV   R8,RDX    // R8:=_EDX
  MOV   RDX, RSP  // RDX:=Stack
  SUB   RSP, 20h
  CALL MyAllMethodsHandler2
  ADD   RSP, 20h  //Restore stack
  POP   R9
end;
{$else}

procedure MyAllMethodsHandler;   //original x86 code
//  On entry:
//  EAX = Self pointer
//  EDX, ECX = param1 and param2
//  STACK = param3... paramcount
asm
  push 0
  push ecx
  push edx
  mov edx, esp
  add edx, 16 // was 12
  pop ecx
  call MyAllMethodsHandler2
  pop ecx
  mov edx, [esp]
  add esp, eax
  mov [esp], edx
  mov eax, ecx
end;
{$endif}

**Comment by carlokok** [comment] 2015-11-23 13:59
I would create a record with all registers in it:
```
X64Registers = record
{$IFDEF WINDOWS}
  RCX, RDX, R8, R9: IntPtr;
  XMM0, XMM1, XMM2, XMM3: Double;
{$ELSE}
 RDI, RSI, RDX, RCX, R8, R9: Int64;
 XMM0, XMM1, XMM2, XMM3, XMM4, XMM5, XMM6 and XMM7: Double;
{$ENDIF}
end;
```
then in the body, allocate enough stack space for this (sizeof(record)), set all fields, pass the field address as the first parameter to MyAllMethodsHandler2 (Which has to be platform specific too)

**Comment by cutec-chris** [comment] 2015-12-11 12:05
This issue is also the cause for callbacks not working on 64bit right?

**Comment by carlokok** [comment] 2015-12-11 12:29
Yes.

**Comment by ccy** [comment] 2016-10-27 14:12
Any news on this issue?  It has been dragged too long.

**Comment by carlokok** [comment] 2016-10-27 14:25
@ccy: pull requests for this features are welcome.

**Comment by cutec-chris** [comment] 2016-10-27 18:40
Yeah, but seems that nobody here has the knowledge to fix it, carlokok what would you need to fix it ? Maybe we can collect an bounty value ?

**Comment by ccy** [comment] 2017-06-12 07:45
The solution from [stackoverflow.com](https://stackoverflow.com/questions/33648962/compiling-pascalscript-in-64-bit-mode-events-not-working#) seems working.

**Comment by carlokok** [comment] 2017-06-12 12:44
This should be fixed now.

**Comment by carlokok** [comment] 2017-06-12 12:44
thanks!

**Closed by carlokok** 2017-06-12 12:44 UTC
